"""LaTeX symbols.

LaTeX base and math symbols.

    Typical usage

    Warp:
    `\\xi`
    Output:
    `ξ`
"""

import keypirinha as kp

MAPPING_SYMBOLS = [
    # Main punctuation
    ["--", "‒"],
    # Capital Greek Letters
    ["\\Alpha", "Α"], # additional
    ["\\Beta", "Β"], # additional
    ["\\Gamma", "Γ"],
    ["\\Delta", "Δ"],
    ["\\Epsilon", "Ε"], # additional
    ["\\Zeta", "Ζ"], # additional
    ["\\Eta", "Η"], # additional
    ["\\Theta", "Θ"],
    ["\\Iota", "Ι"], # additional
    ["\\Kappa", "Κ"], # additional
    ["\\Lambda", "Λ"],
    ["\\Mu", "Μ"], # additional
    ["\\Nu", "Ν"], # additional
    ["\\Xi", "Ξ"],
    ["\\Omicron", "Ο"], # additional
    ["\\Pi", "Π"],
    ["\\Rho", "Ρ"], # additional
    ["\\Sigma", "Σ"],
    ["\\Tau", "Τ"], # additional
    ["\\Upsilon", "Υ"],
    ["\\Phi", "Φ"],
    ["\\Chi", "Χ"], # additional
    ["\\Psi", "Ψ"],
    ["\\Omega", "Ω"],
    # Small Greek Letters
    ["\\alpha", "α"],
    ["\\beta", "β"],
    ["\\gamma", "γ"],
    ["\\digamma", "Ϝ"],
    ["\\delta", "δ"],
    ["\\epsilon", "ε"],
    ["\\zeta", "ζ"],
    ["\\eta", "η"],
    ["\\theta", "θ"],
    ["\\iota", "ι"],
    ["\\kappa", "κ"],
    ["\\lambda", "λ"],
    ["\\mu", "μ"],
    ["\\nu", "ν"],
    ["\\xi", "ξ"],
    ["\\omicron", "ο"], # additional
    ["\\pi", "π"],
    ["\\rho", "ρ"],
    ["\\sigmaf", "ς"], # additional
    ["\\sigma", "σ"],
    ["\\tau", "τ"],
    ["\\upsilon", "υ"],
    ["\\phi", "φ"],
    ["\\chi", "χ"],
    ["\\psi", "ψ"],
    ["\\omega", "ω"],
    # Math Small Greek Letters
    ["\\mathalpha", "𝛼"], # additional
    ["\\mathbeta", "𝛽"], # additional
    ["\\mathgamma", "𝛾"], # additional
    ["\\mathdelta", "𝛿"], # additional
    ["\\vardelta", "𝜕"], # additional
    ["\\mathepsilon", "𝜖"], # additional
    ["\\varepsilon", "𝜀"],
    ["\\mathzeta", "𝜁"], # additional
    ["\\matheta", "𝜂"], # additional
    ["\\maththeta", "𝜃"], # additional
    ["\\vartheta", "𝜗"],
    ["\\mathiota", "𝜄"], # additional
    ["\\varkappa", "𝜘"],
    ["\\mathkappa", "𝜅"], # additional
    ["\\mathlambda", "𝜆"], # additional
    ["\\mathmu", "𝜇"], # additional
    ["\\mathnu", "𝜈"], # additional
    ["\\mathxi", "𝜉"], # additional
    ["\\mathomicron", "𝜊"], # additional
    ["\\varpi", "𝜛"],
    ["\\mathpi", "𝜋"], # additional
    ["\\mathrho", "𝜌"], # additional
    ["\\varrho", "𝜚"],
    ["\\varsigma", "𝜍"],
    ["\\mathsigma", "𝜎"], # additional
    ["\\mathtau", "𝜏"], # additional
    ["\\mathupsilon", "𝜐"], # additional
    ["\\varphi", "𝜑"],
    ["\\mathphi", "𝜙"], # additional
    ["\\mathchi", "𝜒"], # additional
    ["\\mathpsi", "𝜓"], # additional
    ["\\mathomega", "𝜔"], # additional
    # Hebrew Letters (Math)
    ["\\aleph", "ℵ"],
    ["\\beth", "ℶ"],
    ["\\daleth", "ℸ"],
    ["\\gimel", "ℷ"],
    # Delimiters
    ["\\vert", "|"],
    ["\\|", "‖ "],
    ["\\Vert", "‖"],
    ["\\langle", "〈"],
    ["\\rangle", "〉"],
    ["\\lfloor", "⌊"],
    ["\\rfloor", "⌋"],
    ["\\lceil", "⌈"],
    ["\\rceil", "⌉"],
    ["\\backslash", "\\"],
    ["\\Uparrow", "⇑"],
    ["\\uparrow", "↑"],
    ["\\Downarrow", "⇓"],
    ["\\downarrow", "↓"],
    ["\\llcorner", "⌞"],
    ["\\lrcorner", "⌟"],
    ["\\ulcorner", "⌜"],
    ["\\urcorner", "⌝"],
    # Math Symbols (Binary Operation/Relation Symbols)
    ["-", "−"], # (minus) additional
    ["\\divslash", "∕"], # additional
    ["\\sum", "∑"],
    ["\\prod", "∏"],
    ["\\coprod", "∐"],
    ["\\int", "∫"],
    ["\\oint", "∮"],
    ["\\iint", "∬"],
    ["\\biguplus", "⨄"],
    ["\\bigcap", "⋂"],
    ["\\bigcup", "⋃"],
    ["\\bigoplus", "⨁"],
    ["\\bigotimes", "⨂"],
    ["\\bigodot", "⨀"],
    ["\\bigvee", "⋁"],
    ["\\bigwedge", "⋀"],
    ["\\bigsqcup", "⨆"],
    ["\\ast", "*"],
    ["\\star", "⋆"],
    ["\\cdot", "⋅"],
    ["\\circ", "○"],
    ["\\bullet", "●"],
    ["\\bigcirc", "◯"],
    ["\\diamond", "⋄"],
    ["\\times", "×"],
    ["\\div", "÷"],
    ["\\centerdot", "·"],
    ["\\circledast", "⊛"],
    ["\\circledcirc", "⊚"],
    ["\\circleddash", "⊝"],
    ["\\dotplus", "∔"],
    ["\\divideontimes", "⋇"],
    ["\\pm", "±"],
    ["\\mp", "∓"],
    ["\\amalg", "⨿"],
    ["\\odot", "⊙"],
    ["\\ominus", "⊖"],
    ["\\oplus", "⊕"],
    ["\\oslash", "⊘"],
    ["\\otimes", "⊗"],
    ["\\vr", "≀"],
    ["\\box", "□"],
    ["\\boxplus", "⊞"],
    ["\\boxminus", "⊟"],
    ["\\boxtimes", "⊠"],
    ["\\boxdot", "⊡"],
    ["\\square", "□ "],
    ["\\cap", "∩"],
    ["\\cup", "∪"],
    ["\\uplus", "⊎"],
    ["\\sqcap", "⊓"],
    ["\\sqcup", "⊔"],
    ["\\wedge", "∧"],
    ["\\vee", "∨"],
    ["\\dagger", "†"],
    ["\\dag", "† "],
    ["\\ddagger", "‡"],
    ["\\ddag", "‡ "],
    ["\\barwedge", "⊼"],
    ["\\wedgebar", "⩟"], # additional
    ["\\curlywedge", "⋏"],
    ["\\Cap", "⋒"],
    ["\\bot", "⊥"],
    ["\\intercal", "⊺"],
    ["\\doublebarwedge", "⩞"],
    ["\\wedgedoublebar", "⩠"], # additional
    ["\\lhd", "⊲"],
    ["\\rhd", "⊳"],
    ["\\triangleleft", "◁"],
    ["\\triangleright", "▷"],
    ["\\unlhd", "⊴ "],
    ["\\unrhd", "⊵ "],
    ["\\bigtriangleup", "△"],
    ["\\bigtriangledown", "▽"],
    ["\\setminus", "∖"],
    ["\\barvee", "⊽"], # additional
    ["\\veebar", "⊻"],
    ["\\curlyvee", "⋎"],
    ["\\Cup", "⋓"],
    ["\\top", "⊤"],
    ["\\veedoublebar", "⩠"], # additional
    ["\\doublebarvee", "⩞"], # additional
    ["\\rightthreetimes", "⋌"],
    ["\\leftthreetimes", "⋋"],
    ["\\equiv", "≡"],
    ["\\cong", "≅"],
    ["\\neq", "≠"],
    ["\\sim", "∼"],
    ["\\simeq", "≃"],
    ["\\approx", "≈"],
    ["\\asymp", "≍"],
    ["\\doteq", "≐"],
    ["\\propto", "∝"],
    ["\\models", "⊨ "],
    ["\\leq", "≤"],
    ["\\prec", "≺"],
    ["\\preceq", "≼"],
    ["\\ll", "≪"],
    ["\\subset", "⊂"],
    ["\\subseteq", "⊆"],
    ["\\sqsubset", "⊏"],
    ["\\sqsubseteq", "⊑"],
    ["\\dashv", "⊣"],
    ["\\in", "∈"],
    ["\\geq", "≥"],
    ["\\succ", "≻"],
    ["\\succeq", "≽"],
    ["\\gg", "≫"],
    ["\\supset", "⊃"],
    ["\\supseteq", "⊇"],
    ["\\sqsupset", "⊐"],
    ["\\sqsupseteq", "⊒"],
    ["\\vdash", "⊢"],
    ["\\ni", "∋"],
    ["\\perp", "⟂"],
    ["\\mid", "∣"],
    ["\\parallel", "∥"],
    ["\\bowtie", "⋈"],
    ["\\join", "⨝"],
    ["\\ltimes", "⋉"],
    ["\\rtimes", "⋊"],
    ["\\smile", "⌣"],
    ["\\frown", "⌢"],
    ["\\notin", "∉"],
    ["\\approxeq", "≊"],
    ["\\thicksim", "~"],
    ["\\backsim", "∽"],
    ["\\backsimeq", "⋍"],
    ["\\triangleq", "≜"],
    ["\\circeq", "≗"],
    ["\\bumpeq", "≏"],
    ["\\Bumpeq", "≎"],
    ["\\doteqdot", "≑"],
    ["\\thickapprox", "≈ "],
    ["\\fallingdotseq", "≒"],
    ["\\risingdotseq", "≓"],
    ["\\varpropto", "∝ "],
    ["\\therefore", "∴"],
    ["\\because", "∵"],
    ["\\eqcirc", "≖"],
    ["\\neq", "≠"],
    ["\\leqq", "≦"],
    ["\\leqslant", "⩽"],
    ["\\lessapprox", "⪅"],
    ["\\lll", "⋘"],
    ["\\lessdot", "⋖"],
    ["\\lesssim", "≲"],
    ["\\eqslantless", "⪕"],
    ["\\precsim", "≾"],
    ["\\precapprox", "⪷"],
    ["\\Subset", "⋐"],
    ["\\subseteqq", "⫅"],
    ["\\preccurlyeq", "≼"],
    ["\\curlyeqprec", "⋞"],
    ["\\blacktriangleleft", "⏴"],
    ["\\trianglelefteq", "⊴"],
    ["\\vartriangleleft", "◁ "],
    ["\\geqq", "≧"],
    ["\\geqslant", "⩾"],
    ["\\gtapprox", "⪆"],
    ["\\ggg", "⋙"],
    ["\\gtrdot", "⋗"],
    ["\\gtrsim", "≳"],
    ["\\eqslantgtr", "⪖"],
    ["\\succsim", "≿"],
    ["\\succapprox", "⪸"],
    ["\\Supset", "⋑"],
    ["\\supseteqq", "⫆"],
    ["\\succcurlyeq", "≽"],
    ["\\curlyeqsucc", "⋟"],
    ["\\blacktriangleright", "⏵"],
    ["\\trianglerighteq", "⊵"],
    ["\\vartriangleright", "▷ "],
    ["\\lessgtr", "≶"],
    ["\\lesseqgtr", "⋚"],
    ["\\lesseqqgtr", "⪋"],
    ["\\gtreqqless", "⪌"],
    ["\\gtreqless", "⋛"],
    ["\\gtrless", "≷"],
    ["\\backepsilon", "϶"],
    ["\\between", "≬"],
    ["\\pitchfork", "⋔"],
    ["\\shortmid", "❘"],
    ["\\smallfrown", "⏜"],
    ["\\smallsmile", "⏝"],
    ["\\Vdash", "⊩"],
    ["\\vDash", "⊨"],
    ["\\Vvdash", "⊪"],
    ["\\shortparallel", "∥ "],
    ["\\nshortparallel", "∦ "],
    ["\\ncong", "≇"],
    ["\\ncong", "≇"],
    ["\\nmid", "∤"],
    ["\\nparallel", "∦"],
    ["\\nshortmid", "∤ "],
    ["\\nsim", "≁"],
    ["\\nVDash", "⊯"],
    ["\\nvDash", "⊭"],
    ["\\nvdash", "⊬"],
    ["\\ntriangleleft", "⋪"],
    ["\\ntrianglelefteq", "⋬"],
    ["\\ntriangleright", "⋫"],
    ["\\ntrianglerighteq", "⋭"],
    ["\\nleq", "≰"],
    # ["\\nleqq", ""],
    # ["\\nleqslant", ""],
    ["\\nless", "≮"],
    ["\\nprec", "⊀"],
    ["\\npreceq", "⋠"], # different
    ["\\precnapprox", "⪹"],
    ["\\precnsim", "⋨"],
    ["\\lnapprox", "⪉"],
    ["\\lneq", "⪇"],
    ["\\lneqq", "≨"],
    ["\\lnsim", "⋦"],
    # ["\\lvertneqq", ""],
    ["\\ngeq", "≱"],
    # ["\\ngeqq", ""],
    # ["\\ngeqslant", ""],
    ["\\ngtr", "≯"],
    ["\\nsucc", "⊁"],
    ["\\nsuccceq", "⋡"], # different
    ["\\succnapprox", "⪺"],
    ["\\succnsim", "⋩"],
    ["\\gnapprox", "⪊"],
    ["\\gneq", "⪈"],
    ["\\gneqq", "≩"],
    ["\\gnsim", "⋧"],
    # ["\\gvertneqq", ""],
    ["\\nsubseteq", "⊈"],
    ["\\nsupseteq", "⊉"],
    # ["\\nsubseteqq", ""],
    # ["\\nsupseteqq", ""],
    ["\\subsetneq", "⊊"],
    ["\\supsetneq", "⊋"],
    ["\\subsetneqq", "⫋"],
    ["\\supsetneqq", "⫌"],
    ["\\varsubsetneq", "⊊ "],
    ["\\varsupsetneq", "⊋ "],
    ["\\varsubsetneqq", "⫋ "],
    ["\\varsupsetneqq", "⫌ "],
    # Arrow Symbols
    ["\\leftarrow", "←"],
    ["\\Leftarrow", "⇐"],
    ["\\rightarrow", "→"],
    ["\\Rightarrow", "⇒"],
    ["\\leftrightarrow", "↔"],
    ["\\Leftrightarrow", "⇔"],
    ["\\longleftarrow", "⟵"],
    ["\\Longleftarrow", "⟸"],
    ["\\longrightarrow", "⟶"],
    ["\\Longrightarrow", "⟹"],
    ["\\longleftrightarrow", "⟷"],
    ["\\Longleftrightarrow", "⟺"],
    ["\\uparrow", "↑"],
    ["\\Uparrow", "⇑"],
    ["\\downarrow", "↓"],
    ["\\Downarrow", "⇓"],
    ["\\updownarrow", "↕"],
    ["\\Updownarrow", "⇕"],
    ["\\mapsto", "↦"],
    ["\\hookleftarrow", "↩"],
    ["\\leftharpoonup", "↼"],
    ["\\leftharpoondown", "↽"],
    ["\\rightleftharpoons", "⇌"],
    ["\\longmapsto", "⟼"],
    ["\\hookrightarrow", "↪"],
    ["\\rightharpoonup", "⇀"],
    ["\\rightharpoondown", "⇁"],
    ["\\leadsto", "⇝"],
    ["\\nearrow", "↗"],
    ["\\searrow", "↘"],
    ["\\swarrow", "↙"],
    ["\\nwarrow", "↖"],
    ["\\dashrightarrow", "⇢"],
    ["\\leftrightarrows", "⇆"],
    ["\\leftarrowtail", "↢"],
    ["\\curvearrowleft", "↶"],
    ["\\upuparrows", "⇈"],
    ["\\multimap", "⊸"],
    ["\\rightleftarrows", "⇄"],
    ["\\twoheadrightarrow", "↠"],
    ["\\Rsh", "↱"],
    ["\\downharpoonright", "⇂"],
    ["\\dashleftarrow", "⇠"],
    ["\\Lleftarrow", "⇚"],
    ["\\looparrowleft", "↫"],
    ["\\circlearrowleft", "↺"],
    ["\\upharpoonleft", "↿"],
    ["\\leftrightsquigarrow", "↭"],
    ["\\rightrightarrows", "⇉"],
    ["\\rightarrowtail", "↣"],
    ["\\curvearrowright", "↷"],
    ["\\downdownarrows", "⇊"],
    ["\\rightsquigarrow", "⇝"],
    ["\\leftleftarrows", "⇇"],
    ["\\twoheadleftarrow", "↞"],
    ["\\leftrightharpoons", "⇋"],
    ["\\Lsh", "↰"],
    ["\\downharpoonleft", "⇃"],
    ["\\looparrowright", "↬"],
    ["\\circlearrowright", "↻"],
    ["\\upharpoonright", "↾"],
    ["\\nleftarrow", "↚"],
    ["\\nrightarrow", "↛"],
    ["\\nLeftarrow", "⇍"],
    ["\\nRightarrow", "⇏"],
    ["\\nleftrightarrow", "↮"],
    ["\\nLeftrightarrow", "⇎"],
    # Misc
    ["\\florin", "ƒ"], # additional
    ["\\acd", "∿"], # additional
    ["\\degree", "°"], # additional
    ["\\celsius", "℃"], # additional
    ["\\fahrenheit", "℉"], # additional
    ["\\kelvin", "K"], # additional
    ["\\infty", "∞"],
    ["\\nabla", "∇"],
    ["\\partial", "∂"],
    ["\\eth", "ð"],
    ["\\clubsuit", "♣"],
    ["\\diamondsuit", "♢"],
    ["\\heartsuit", "♡"],
    ["\\spadesuit", "♠"],
    ["\\cdots", "⋯"],
    ["\\vdots", "⋮"],
    ["\\ldots", "⋰"],
    ["\\ddots", "⋱"],
    ["\\Im", "𝕴"],
    ["\\Re", "𝕽"],
    ["\\forall", "∀"],
    ["\\exists", "∃"],
    ["\\nexists", "∄"],
    ["\\emptyset", "∅"],
    ["\\varnothing", "∅ "],
    ["\\o", " ∅"],
    ["\\O", " ∅ "],
    ["\\imath", "𝚤"],
    ["\\jmath", "𝚥"],
    ["\\ell", "ℓ"],
    ["\\iiiint", "∫∫∫∫"],
    ["\\iiint", "∭"],
    ["\\iint", "∬"],
    ["\\sharp", "♯"],
    ["\\sharp", "♭"],
    ["\\natural", "♮"],
    ["\\Bbbk", "𝕜"],
    ["\\bigstar", "★"],
    ["\\diagdown", "⟍"],
    ["\\diagup", "⟋"],
    ["\\Diamond", "◊"],
    ["\\Finv", "Ⅎ"],
    ["\\Game", "⅁"],
    ["\\hbar", "ℏ"],
    ["\\hslash", "ℏ "],
    ["\\lozenge", "◊ "],
    ["\\mho", "℧"],
    ["\\prime", "′"],
    ["\\square", " □"],
    ["\\surd", "√"],
    ["\\wp", "℘"],
    ["\\angle", "∠"],
    ["\\measuredangle", "∡"],
    ["\\sphericalangle", "∢"],
    ["\\complement", "∁"],
    ["\\triangledown", "▿"],
    ["\\triangle", "▵"],
    ["\\vartriangle", "△ "],
    ["\\blacklozenge", "⧫"],
    ["\\blacksquare", "■"],
    ["\\blacktriangle", "▲"],
    ["\\blacktriangledown", "▼"],
    ["\\backprime", "‵"],
    ["\\circledS", "Ⓢ"],
    # Chemical Symbols
    ["\\benzene", "⌬"], # additional
    ["\\cbenzene", "⏣"], # additional
    # Additional (Text Mode)
    ["\\ae", "æ"],
    ["\\AE", "Æ"],
    ["\\i", "ı"],
    ["\\ss", "ß"],
    ["\\P", "¶"],
    ["\\copyright", "©"],
    ["\\j", "ȷ"],
    ["\\S", "§"],
    ["\\pounds", "£"]]

def assign_cat(plugin):
    """Assigns `symbols` module mapping to the `Warp` plugin."""

    items = []
    for item in MAPPING_SYMBOLS:
        items.append(
            plugin.create_item(
                category=plugin.CATEGORY_SYMBOLS,
                label=item[0],
                short_desc=item[1],
                target=item[1],
                args_hint=kp.ItemArgsHint.FORBIDDEN,
                hit_hint=kp.ItemHitHint.IGNORE))
    return items